### ISSUE TITLE
Too much graphics memory!

### ISSUE THREAD

**Issue by intjun** [bryandlee/animegan2-pytorch#1]
RuntimeError: CUDA out of memory. Tried to allocate 12.44 GiB

**Comment by Sencc** [comment]
I also encountered this problem,how to solve this problem?

**Comment by bryandlee** [comment]
What's the size of your image? Maybe try the cpu mode? It only takes a few seconds for 1280x853 image on i7-9700K.

**Comment by seawater668** [comment]
@bryandlee 为什么使用GPU运行test.py都显示gpu显存不够，但是使用cpu就可以呢？我的gpu显存是12G的
