### ISSUE TITLE
What is the Torch version？

### ISSUE THREAD

**Issue by binglebai** [bryandlee/animegan2-pytorch#15]
my torch.__version__ is 1.2.0 and have problem about torch.load() .
What version do you use?

`RuntimeError: ./face_paint_512_v2.pt is a zip archive (did you mean to use torch.jit.load()?)`

**Comment by bryandlee** [comment]
I'm using 1.10.0. I guess you need torch >= 1.7.1

**Comment by binglebai** [comment]
> I'm using 1.10.0. I guess you need torch >= 1.7.1

think u for ur reply
