### ISSUE TITLE
Face model

### ISSUE THREAD

**Issue by doublex** [bryandlee/animegan2-pytorch#2]
Hello,
Is this model still available for testing?
https://drive.google.com/file/d/10T6F3-_RFOCJn6lMb-6mRmcISuYWJXGc/view?usp=sharing
Best wishes!

**Comment by bryandlee** [comment]
Hi, the model is still available. Let me know if the link doesn't work.

**Comment by doublex** [comment]
Hi, there is only an "archive" folder.

**Comment by bryandlee** [comment]
The download button in the top-right corner should work.

**Comment by doublex** [comment]
Sorry for disturbing!
