### ISSUE TITLE
Concern about version of Tensorflow and python

### ISSUE THREAD

**Issue by ngockimhoang** [bryandlee/animegan2-pytorch#31]
In the basic usage, you say that
Weight Conversion from the Original Repo (Requires TensorFlow 1.x)
TensorFlow 1.x can only installed for python2.
However the code in test.py is using python3 syntax.
How did you manage to make it work?

**Comment by ngockimhoang** [comment]
I got it, it is actually tensorflow-gpu 1.15.0, not tensorflow. The require version of python is 3.6
You should really state it more clearly in README.
I figured it out by digging to original repo.

**Comment by PrincessAkira** [comment]
Can you edit the readme maybe?
Im trying since hours to get this to work.

regards
lilly

**Comment by bryandlee** [comment]
Got it, thanks.
