### ISSUE TITLE
PNG images with transparent background are not supported

### ISSUE THREAD

**Issue by njfanxun** [bryandlee/animegan2-pytorch#53]
The portrait is on a png image with a transparent background and cannot be stylized。How to modify the code to support it?

**Comment by bryandlee** [comment]
Hi, can I see the error message?

**Comment by njfanxun** [comment]
no error，but the generated image will automatically fill the background。You can try it out with a png with an alpha channel in the background. I think maybe the alpha value is discarded when the image data is processed. But I don't know how to modify the code. code reference demo.ipynb。

**Comment by njfanxun** [comment]
![1](https://user-images.githubusercontent.com/1555047/155689070-007698e6-eef3-497a-8aec-b26ffe1eb2dc.png)
![anime_full_1](https://user-images.githubusercontent.com/1555047/155689121-e4bff1b1-6c1e-43bd-bf27-248df3a8736e.png)

**Comment by bryandlee** [comment]
Here you go, replace the last cell in demo.ipynb with this:

```python
import requests
from torchvision.transforms.functional import to_tensor, to_pil_image

# Load image
image = Image.open(requests.get("https://user-images.githubusercontent.com/1555047/155689070-007698e6-eef3-497a-8aec-b26ffe1eb2dc.png", stream=True).raw)
image_rgb = image.convert("RGB")

# Detect faces & resize image s.t. face size = 256
face_detector = get_dlib_face_detector()
landmarks = face_detector(image_rgb)
landmarks = np.array(landmarks)
mean_face_size = (landmarks.max(axis=1) - landmarks.min(axis=1)).mean()

resize_ratio = 256 / max(mean_face_size, 32)
image_inference_size = (np.array(image.size) * resize_ratio).astype(int)
image_inference_size -= image_inference_size % 4
print(image_inference_size)
image_rgb = image_rgb.resize(image_inference_size, Image.LANCZOS)

# Model inference
model_input = to_tensor(image_rgb).unsqueeze(0) * 2 - 1
with torch.inference_mode():
    image_output = model(model_input.to(device))
image_output = (image_output * 0.5 + 0.5).clip(0, 1)
image_output = to_pil_image(image_output.cpu()[0])

# Resize image back to the original size & mode
image_output = image_output.resize(image.size, Image.LANCZOS).convert(image.mode)
if image.mode == "RGBA":  # <<<<< THIS PART HANDLES WHAT YOU WANTED
    alpha = image.split()[-1]
    image_output.putalpha(alpha)

display(image_output)
```

The output will look like this:

![image](https://user-images.githubusercontent.com/26464535/156568832-5ab8ed26-c51f-4fc4-9315-32c65b29c2f9.png)

+) image size and face ratio does matter, you can get cleaner results if you use aligned & cropped faces

![image](https://user-images.githubusercontent.com/26464535/156563543-aa9473fd-5d00-4740-beb6-fb27c7d55c76.png)

**Comment by njfanxun** [comment]
oh awesome thank you so much

**Comment by seawater668** [comment]
@bryandlee 我用test.py 跑出如下结果，应该怎么修改代码呢
![image](https://user-images.githubusercontent.com/29244715/218697482-0c47eea7-5c9e-4fd4-abd8-1f17c1d2585c.png)
