### ISSUE TITLE
How to Convert Full Body Photo

### ISSUE THREAD

**Issue by haoxionga** [bryandlee/animegan2-pytorch#66]
Hello, when I use the [face_paint_512_v2.pt] model to convert the full body photo, it is very ugly, but the photo containing only the face is good, how can I combine the face only and the full body photo together? Does the model need to be retrained?

like this
![anime](https://user-images.githubusercontent.com/17867939/160569827-f4d72600-1330-4078-b3c7-630dc9980128.png)

photo1 use other app,i think its use animegan2.
photo2 convert full body photo.its ugly width face
photo3 only convert face, its nice.and face like photo 1

**Comment by Youngon** [comment]
what app do you use to get photo1？

**Comment by bryandlee** [comment]
You can use face detection & segmentation models
![image](https://user-images.githubusercontent.com/26464535/162569101-d92f4d67-a185-4f71-b0fb-ccd293b40ccc.png)

**Comment by zhouqihao** [comment]
> what app do you use to get photo1？



>

**Comment by haoxionga** [comment]
> what app do you use to get photo1？



> 



> what app do you use to get photo1？

修图家， apple store

**Comment by haoxionga** [comment]
> You can use face detection & segmentation models ![image](https://user-images.githubusercontent.com/26464535/162569101-d92f4d67-a185-4f71-b0fb-ccd293b40ccc.png)

thanks，I will try

**Comment by aycaecemgul** [comment]
@zhouqihao Hi! I am trying the same approach, can you share which model you used for creating the segmentation mask? Just using the detection bbox yields bad results.

**Comment by ywdong** [comment]
> You can use face detection & segmentation models您可以使用人脸检测和分割模型 ![image](https://user-images.githubusercontent.com/26464535/162569101-d92f4d67-a185-4f71-b0fb-ccd293b40ccc.png)

Can u share the code about this？ Many thx~
